### ISSUE TITLE
LEDs won't light up

### ISSUE THREAD

**Issue by joveaaron** [SteveBenz/PS2KeyboardHost#3]
Hello there, after seeing the problems with PS2KeyAdvanced, I decided to move to this library, but it seems like I am not able to make the LEDs blink. Using the SelfTest example, if I press the Q, W and E keys, no led blinks.
I am using an Arduino Uno R3 (good clone with atmega16u2, basically a 1:1 R3 clone) and a Microsoft MultiMedia Keyboard 1.0A (if that is somehow useful)
Also seems to make the keyboard hang when pressing the "1" key.

**Comment by SteveBenz** [comment]
Dunno what to say - I use this library as a daily-driver for an IBM Model M, it all works for me.  It also works on fine with a couple of other keyboards I tested it with.  The PS2KeyAdvanced library worked for my keyboards too, just without all the features I'd like.  You might try a different keyboard (grab one at Goodwill if you don't have one lying around).  Given that the keyboard can hang altogether, I'd be suspicious of the connections.  Having another keyboard would help validate that.

**Comment by joveaaron** [comment]
Hello, I am now using the library more extensively, and I have found that using disableBreakCodes() returns false, indicating the keyboard hasn't responded appropriately. Everything else not involved in sending commands to the keyboard works fine. I have ensured the keyboard works correctly, as I use it with my Windows 98 PC, and the NumLock LEDs work.
